In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt,seaborn as sns

In [46]:
data=pd.read_csv('C:/Users/prade/Desktop/imarticus files/DATASETS/machine learning/RANDOM FOREST/Heart.csv')
data.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [47]:
df=data.copy(deep=True)

In [48]:
df.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [49]:
df.shape

(303, 15)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  303 non-null    int64  
 1   Age         303 non-null    int64  
 2   Sex         303 non-null    int64  
 3   ChestPain   303 non-null    object 
 4   RestBP      303 non-null    int64  
 5   Chol        303 non-null    int64  
 6   Fbs         303 non-null    int64  
 7   RestECG     303 non-null    int64  
 8   MaxHR       303 non-null    int64  
 9   ExAng       303 non-null    int64  
 10  Oldpeak     303 non-null    float64
 11  Slope       303 non-null    int64  
 12  Ca          299 non-null    float64
 13  Thal        301 non-null    object 
 14  AHD         303 non-null    object 
dtypes: float64(2), int64(10), object(3)
memory usage: 35.6+ KB


In [51]:
df.isnull().count()

Unnamed: 0    303
Age           303
Sex           303
ChestPain     303
RestBP        303
Chol          303
Fbs           303
RestECG       303
MaxHR         303
ExAng         303
Oldpeak       303
Slope         303
Ca            303
Thal          303
AHD           303
dtype: int64

In [52]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [53]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [54]:
df.shape

(303, 14)

In [55]:
missvalue=df.isnull().sum()
missvalue[missvalue>0]

Ca      4
Thal    2
dtype: int64

In [56]:
df[df.Ca.isnull()]

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
166   52    1    nonanginal     138   223    0        0    169      0   
192   43    1  asymptomatic     132   247    1        2    143      1   
287   58    1    nontypical     125   220    0        0    144      0   
302   38    1    nonanginal     138   175    0        0    173      0   

     Oldpeak  Slope  Ca        Thal  AHD  
166      0.0      1 NaN      normal   No  
192      0.1      2 NaN  reversable  Yes  
287      0.4      2 NaN  reversable   No  
302      0.0      1 NaN      normal   No

In [57]:
df[df.Thal.isnull()]

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
87    53    0    nonanginal     128   216    0        2    115      0   
266   52    1  asymptomatic     128   204    1        0    156      1   

     Oldpeak  Slope   Ca Thal  AHD  
87       0.0      1  0.0  NaN   No  
266      1.0      2  0.0  NaN  Yes

In [58]:
df.Ca.value_counts()

0.0    176
1.0     65
2.0     38
3.0     20
Name: Ca, dtype: int64

In [59]:
df.groupby(['ChestPain','Sex','Ca'])['Ca'].size()

ChestPain     Sex  Ca 
asymptomatic  0    0.0    25
                   1.0     2
                   2.0     9
                   3.0     4
              1    0.0    41
                   1.0    32
                   2.0    20
                   3.0    10
nonanginal    0    0.0    26
                   1.0     9
              1    0.0    31
                   1.0    11
                   2.0     2
                   3.0     5
nontypical    0    0.0    11
                   1.0     4
                   2.0     3
              1    0.0    26
                   1.0     4
                   3.0     1
typical       0    0.0     3
                   2.0     1
              1    0.0    13
                   1.0     3
                   2.0     3
Name: Ca, dtype: int64

In [60]:
df.Ca.fillna(0.0,inplace=True)

In [61]:
df.groupby(['ChestPain','Sex','Thal'])['Thal'].size()

ChestPain     Sex  Thal      
asymptomatic  0    fixed          1
                   normal        27
                   reversable    12
              1    fixed         11
                   normal        26
                   reversable    66
nonanginal    0    normal        31
                   reversable     3
              1    fixed          2
                   normal        30
                   reversable    19
nontypical    0    normal        18
              1    fixed          2
                   normal        21
                   reversable     9
typical       0    normal         4
              1    fixed          2
                   normal         9
                   reversable     8
Name: Thal, dtype: int64

In [62]:
df.loc[87,'Thal']='Normal'
df.loc[266,'Thal']='reversable'

In [63]:
missvalue=df.isnull().sum()
missvalue[missvalue>0]

Series([], dtype: int64)

In [64]:
df.AHD.value_counts()

No     164
Yes    139
Name: AHD, dtype: int64

In [65]:
for i in df.select_dtypes(include='object').columns:
    print(i)
    print()
    print(df[i].value_counts())
    print()

ChestPain

asymptomatic    144
nonanginal       86
nontypical       50
typical          23
Name: ChestPain, dtype: int64

Thal

normal        166
reversable    118
fixed          18
Normal          1
Name: Thal, dtype: int64

AHD

No     164
Yes    139
Name: AHD, dtype: int64



In [66]:
df.target=pd.get_dummies(df.AHD,drop_first=True,columns="Target")

C:\Users\prade\AppData\Local\Temp/ipykernel_1332/3635153304.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.target=pd.get_dummies(df.AHD,drop_first=True,columns="Target")


In [67]:
type(df.target)

pandas.core.frame.DataFrame

In [68]:
df.target.value_counts()

Yes
0      164
1      139
dtype: int64

In [69]:
df.Thal.replace('Normal','normal',inplace=True)

In [70]:
df.Thal.replace({'normal':0,'reversable':1,'fixed':2},inplace=True)

In [71]:
df.ChestPain.replace({'asymptomatic':0,'nonanginal':1,'nontypical':2,'typical':3},inplace=True)

In [72]:
df.drop('AHD',axis=1,inplace=True)

In [73]:
df=pd.concat([df,df.target],axis=1)

In [74]:
df.columns

Index(['Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR',
       'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'Yes'],
      dtype='object')

In [75]:
df.rename(columns={'Yes':'Target'},inplace=True)

In [76]:
df.columns

Index(['Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR',
       'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'Target'],
      dtype='object')

In [77]:
y = df.iloc[:,-1]
x = df.iloc[:, 0:-1]

In [78]:
x.shape,y.shape

((303, 13), (303,))

In [79]:
df.shape

(303, 14)

In [80]:
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [81]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=100)

In [82]:
rf=RandomForestClassifier(n_jobs=-1)

In [83]:
rf.fit(x_train,y_train)

RandomForestClassifier(n_jobs=-1)

In [84]:
tr_pred=rf.predict(x_train)
test_pred=rf.predict(x_test)

In [85]:
confusion_matrix(y_train,tr_pred)

array([[125,   0],
       [  0, 102]], dtype=int64)

In [86]:
print(classification_report(y_train,tr_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       125
           1       1.00      1.00      1.00       102

    accuracy                           1.00       227
   macro avg       1.00      1.00      1.00       227
weighted avg       1.00      1.00      1.00       227



In [87]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.82      0.95      0.88        39
           1       0.94      0.78      0.85        37

    accuracy                           0.87        76
   macro avg       0.88      0.87      0.87        76
weighted avg       0.88      0.87      0.87        76



In [88]:
confusion_matrix(y_test,test_pred)

array([[37,  2],
       [ 8, 29]], dtype=int64)

In [89]:
y_test.value_counts()

0    39
1    37
Name: Target, dtype: int64

In [90]:
df.head()

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1          3     145   233    1        2    150      0      2.3   
1   67    1          0     160   286    0        2    108      1      1.5   
2   67    1          0     120   229    0        2    129      1      2.6   
3   37    1          1     130   250    0        0    187      0      3.5   
4   41    0          2     130   204    0        2    172      0      1.4   

   Slope   Ca  Thal  Target  
0      3  0.0     2       0  
1      2  3.0     0       1  
2      2  2.0     1       1  
3      3  0.0     0       0  
4      1  0.0     0       0

In [91]:
df.ChestPain.describe()

count    303.000000
mean       0.841584
std        0.960126
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        3.000000
Name: ChestPain, dtype: float64

In [93]:
df.ChestPain.dtype

dtype('int64')

In [94]:
df_feature_imp=pd.DataFrame(zip(x.columns,rf.feature_importances_),columns=['colname','imp'])

In [111]:
df_feature_imp.sort_values(by='imp',ascending=False)

colname       imp
2   ChestPain  0.139015
12       Thal  0.138241
7       MaxHR  0.119341
11         Ca  0.108296
9     Oldpeak  0.085625
0         Age  0.085472
4        Chol  0.084303
3      RestBP  0.075763
8       ExAng  0.059275
10      Slope  0.043227
1         Sex  0.028087
6     RestECG  0.021956
5         Fbs  0.011399

In [112]:
impcols=df.columns[df_feature_imp[df_feature_imp.imp>=0.04].index]

In [113]:
impcols

Index(['Age', 'ChestPain', 'RestBP', 'Chol', 'MaxHR', 'ExAng', 'Oldpeak',
       'Slope', 'Ca', 'Thal'],
      dtype='object')

## Building with RF model with important features

In [106]:
rf.fit(x_train[impcols],y_train)

RandomForestClassifier(n_jobs=-1)

In [107]:
y_pred=rf.predict(x_test[impcols])

In [108]:
y_pred[:10]

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0], dtype=uint8)

In [109]:
confusion_matrix(y_test,y_pred)

array([[37,  2],
       [ 7, 30]], dtype=int64)

In [110]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89        39
           1       0.94      0.81      0.87        37

    accuracy                           0.88        76
   macro avg       0.89      0.88      0.88        76
weighted avg       0.89      0.88      0.88        76

